name: invoice_receipt_generator_web
description: "Responsive invoice and receipt generator for freelancers."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  web: ^0.5.1
  intl: ^0.20.2
  provider: ^6.1.2
  uuid: ^4.4.0
  pdf: ^3.11.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - packages/flutter/fonts/Roboto-Regular.ttf
    - packages/flutter/fonts/Roboto-Bold.ttf
    - packages/flutter/fonts/Roboto-Italic.ttf
    - packages/flutter/fonts/Roboto-BoldItalic.ttf
    - packages/flutter/fonts/NotoSans-Regular.ttf
    - packages/flutter/fonts/NotoSans-Regular.otf
    - packages/flutter/fonts/NotoSansJP-Regular.otf
    - packages/flutter/fonts/NotoSansJP-Regular.ttf
